### ISSUE TITLE
jd01_08

### ISSUE THREAD

**Issue by AlehMeshchanka** [Khmelov/JD2017-09-20#32]
Как получить (узнать) вариант задания по теме jd01_08, если пропустил занятие?

**Comment by antoshk** [comment]
По порядковому номеру в табличке с оценками, либо, если хочется, любое на выбор.

**Comment by AlehMeshchanka** [comment]
Группу в вайбере (телеграмме) для общения никто не создавал?

**Comment by antoshk** [comment]
Скинь номер - добавлю

**Comment by AlehMeshchanka** [comment]
+375295303445

**Comment by antoshk** [comment]
Добавил в чат в вайбере
